# Generated by Django 2.1.5 on 2019-02-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
